### PR TITLE
Add Jinja2 support for systemPrompt & prompt.

### PR DESCRIPTION
**Pull request by jeffqg**
Jinja2 allows more control over prompt building. For example, rather including a summary section that may be empty, you can conditionally include the summary.

Sample usage:

```
// assume agent1 was type=GetCurrentSummaryFromFile
{
  ...,
  "systemPrompt": "{{chat_system_prompt}}{% if \"There is not yet a summary\" not in agent1Output %}\n###Summary of prior conversation\n\n{{ agent1Output }}{% endif %}",
  "jinja2": true
}
```

### CODE REVIEW

**Comment by SomeOddCodeGuy** [comment]
This looks awesome! I'm so sorry for the delayed response; work was crazy the past week.

Let me toy with it tomorrow, and also update the licenses section for jinja, and if it nothing is broken then I'll pull it in. After that I'll merge workflow_locks into prod unless you've seen an issue with them in your own tinkering.

**Comment by SomeOddCodeGuy** [comment]
@jeffqg posting here so that you can see it. I noticed that something about your branching scheme or your github settings was causing your commits to not count as a contributor to the repo on the frontpage. I thought there was just some issue with my repo overall, but someone updated a spelling error on the readme and is now showing as a contributor.

Not sure if it matters to you, but given your contribution you certainly deserve so show up there, so if you'd like to then go find something small, like a word on the readme, to change and make a PR for it. I'll put it through so you show up on the list.

I recommend beforehand checking out this link and making sure your email that you have on the committing account matches the email on your github:

https://stackoverflow.com/questions/40644933/not-showing-as-a-contributor-on-github

**Comment by jeffqg** [comment]
Thank you! There was a gap between my local settings and GitHub. I've been trying out rag via vector db with Chroma in a Python module. I'll package it up and open a PR.

**Comment by SomeOddCodeGuy** [comment]
That works! Though it sounds like it could also be a cool standalone API similar to [the offline wiki](https://github.com/SomeOddCodeGuy/OfflineWikipediaTextApi) as well; if you end up doing that, we could make a connection node that hits the API. RAG is something a lot of folks on /r/LocalLlama would really like, so if you're having good luck with it then that could help a lot of folks.

**Pull request merged**
